server:
  port: 8506
  servlet:
    context-path: /recurso2

eureka:
  instance:
    hostname: localhost
    port: 8505
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8501/autenticacao/oauth/check_token