server:
  port: 8501
  servlet:
    context-path: /autenticacao

eureka:
  instance:
    hostname: localhost
    port: 8505
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth
    username: springaouth
    password: springaouth
  jpa:
    database: POSTGRESQL
    datasource:
      plataform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    show-sql: true

flyway:
  baselineOnMigrate: true