server:
  port: 8501
  servlet:
    context-path: /autenticacao
  ssl:
    enabled: false
    key-alias: demo_rsa_key
    key-store: classpath:demo_rsa_key.keystore
    key-store-password: demo_rsa_key
    key-password: demo_rsa_key

eureka:
  instance:
    hostname: localhost
    port: 8505
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth
    username: springoauth
    password: springoauth
  jpa:
    database: POSTGRESQL
    datasource:
      plataform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    show-sql: true

flyway:
  baselineOnMigrate: true