INSERT INTO OAUTH_CLIENT_DETAILS(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY)
	VALUES ('authorization_code_client', 'resources',
	/*authorization_code_secret*/'$2a$10$8EAEOhp9Qk7ZvxigHJCIbewrVNe1XV/YCB24YJoBS9DmGgNRnmaiS',
	'all', 'client_credentials', 'ADMIN', 10800, 2592000);