server:
  port: 8501
  servlet:
    context-path: /autenticacao

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth
    username: springaouth
    password: springaouth
  jpa:
    database: POSTGRESQL
    datasource:
      plataform: postgres
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    show-sql: true

flyway:
  baselineOnMigrate: true